{% set name = "pytask-stata" %}
{% set version = "0.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytask_stata-{{ version }}.tar.gz
  sha256: ab1d0e9294fc1303dc0e0cdc5e349a293d6abc7330c2fa7dd12fa91d62ef7423

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
  run:
    - click >=8.1.8,!=8.2.0
    - pytask >=0.5.2
    - python >={{ python_min }}

test:
  imports:
    - pytask_stata
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pytask-dev/pytask-stata
  summary: Execute do-files with Stata and pytask.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/pytask-dev/pytask-stata
  doc_url: https://github.com/pytask-dev/pytask-stata

extra:
  recipe-maintainers:
    - tobiasraabe
