{% set name = "pytask-stata" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytask_stata-{{ version }}.tar.gz
  sha256: 04fa9527889c9e236fcabee72f6085429305f51cbb78e405bcdb2f24d30bfdc3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools_scm
    - toml
  run:
    - click
    - pluggy
    - pytask >=0.4
    - python >=3.8

test:
  imports:
    - pytask_stata
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytask-dev/pytask-stata
  summary: Execute do-files with Stata and pytask.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/pytask-dev/pytask-stata
  doc_url: https://github.com/pytask-dev/pytask-stata

extra:
  recipe-maintainers:
    - tobiasraabe
