{% set name = "pytask-stata" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytask_stata-{{ version }}.tar.gz
  sha256: 1b1979730c37c0fc16d8a8511247cf09847d1755209fef302b9bef32a7968121

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
    - toml
  run:
    - pytask >=0.1.7
    - python >=3.7

test:
  imports:
    - pytask_stata
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytask-dev/pytask-stata
  summary: Execute do-files with Stata and pytask.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/pytask-dev/pytask-stata
  doc_url: https://github.com/pytask-dev/pytask-stata

extra:
  recipe-maintainers:
    - tobiasraabe
