{% set name = "pytask-stata" %}
{% set version = "0.5.0" %}
{% set python_min = "3.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytask_stata-{{ version }}.tar.gz
  sha256: 2044f8d68200dd085fb14f220d0387a1c783d9575d69cd7e744b9578c0ad68e2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
  run:
    - click
    - pluggy
    - pytask >=0.4
    - python >={{ python_min }}

test:
  imports:
    - pytask_stata
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pytask-dev/pytask-stata
  summary: Execute do-files with Stata and pytask.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/pytask-dev/pytask-stata
  doc_url: https://github.com/pytask-dev/pytask-stata

extra:
  recipe-maintainers:
    - tobiasraabe
