{% set name = "pytask-stata" %}
{% set version = "0.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytask_stata-{{ version }}.tar.gz
  sha256: bc6b3dbeb6a88a8a985894ea25c42db93920e8793e052589cdd983778e888e0e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
    - toml
  run:
    - pytask >=0.1.0
    - python >=3.6

test:
  imports:
    - pytask_stata
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytask-dev/pytask-stata
  summary: Execute do-files with Stata and pytask.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/pytask-dev/pytask-stata
  doc_url: https://github.com/pytask-dev/pytask-stata

extra:
  recipe-maintainers:
    - tobiasraabe
